restructure Makefile to allow more control of build locations
StanfordLegion/gasnet pull request #3
Opened 2021-01-15 03:42 UTC by streichler

these changes are intended to allow an out-of-source build (e.g. as might be used when embedded in a cmake build)
the default behavior should still match current behavior

2021-01-16 20:55 UTC, bonachea requested changes
Overall looks like good work.

I made a few suggestions for further improvement.

2021-01-16 20:55 UTC, bonachea commented on Makefile
>  # GASNet-EX has not been publicly released yet - contact the GASNet-EX team for access to pre-releases
Not sure if the rules below are dead code, but the comment above is definitely out-of-date. Please update/remove.

2021-01-16 20:55 UTC, bonachea commented on Makefile
> +	make -C $(GASNET_BUILD_DIR) install
`make` should probably be `$(MAKE)`

2021-01-16 20:55 UTC, bonachea commented on Makefile
> +GASNET_CFLAGS ?= -fPIC
Minor nitpick: From a design perspective it's more robust to separate C and CXX flags - as written this assumes whatever options the caller might wish to set are valid for both compilers. This would fail if the caller needed to set something like `-std=c11` or  `-std=c++14`

2021-01-16 20:55 UTC, bonachea commented on Makefile
> +	chmod a+x $(GASNET_BUILD_DIR)/CC.custom
The cruft above and below is really gross and probably reflects what was necessary in ancient versions of the cross-configure scripts.

IIUC the lines above could be replaced with a configure argument like:
```
--with-libs="$$CRAY_UGNI_POST_LINK_OPTS $$CRAY_PMI_POST_LINK_OPTS -Wl,--as-needed,-lugni,-lpmi,--no-as-needed"
```
however these particular options should _already_ appear on the Cray XC in the GASNet makefile fragments and pkgconfig files in the GASNET_LIBS variable, so I suspect the real issue is that variable is (or perhaps was?) being ignored. If your link step pulls in GASNET_LIBS then the lines above can probably be dropped entirely

IIUC The three lines below can/should be replaced with configure arguments exactly as for the non-cross-compile cases, ie:
```
--with-cflags="$(GASNET_CFLAGS)" --with-mpi-cflags="$(GASNET_CFLAGS)" --with-cxxflags="$(GASNET_CXXFLAGS)"
```
in fact that could be factored into a variable and passes to all three configure variants.

Once such changes are made, you should no longer need the compiler wrappers or cross-configure script rewrite. The compiler wrappers are especially unfortunate, because they don't get installed and the installed GASNet makefile fragments and pkgconfig are left pointing to compiler wrappers that probably no longer exist.

2021-01-16 20:55 UTC, bonachea commented on Makefile
>  GASNET_CONFIG ?= configs/config.$(CONDUIT).release
At some point we should discuss the contents of these canned configure arg files, which contain some unnecessary/outdated arguments.

For example, the following arguments no longer exist and are ignored (so harmless, but misleading noise):
* `--with-segment-mmap-max`  (removed in 1.32.0)
* `--disable-portals` (removed in 1.22.0)

For non-cross-compiled systems, all the various `--disable-CONDUIT` arguments could be replaced by simply passing `--disable-auto-conduit-detect` (which disables automatic conduit probing) and then just `--enable-CONDUIT` the one you want. 

The Cray XC cross-configure scripts explicitly pass `--enable-smp --enable-mpi=probe --enable-ofi=probe`, so for that system you'll still need to explicitly disable those three.

2021-01-16 22:07 UTC, streichler commented on Makefile
>  # GASNet-EX has not been publicly released yet - contact the GASNet-EX team for access to pre-releases
Doesn't look like this is showing the updates, but the rules below are still useful and I've updated the comment:

```
- # GASNet-EX has not been publicly released yet - contact the GASNet-EX team for access to pre-releases
+ # the GASNet-EX team makes prerelease snapshots available if you ask nicely -
+ #  this rule is a helper to automatically download one of those
```

2021-01-16 22:10 UTC, streichler commented
> Overall looks like good work.
> 
> I made a few suggestions for further improvement.

Thanks for looking it over!  I agree with nearly everything you suggested, but many of those changes require removing support for ancient versions of gasnet and/or testing the changes on a bunch of systems, so I'd like to address those as separate efforts rather than try to sneak them into this PR.

2021-01-16 22:15 UTC, streichler commented on Makefile
> +GASNET_CFLAGS ?= -fPIC
Agreed, and I'll definitely go back and clean this up.  It's fine for now because we're actually trying to control the build of the GASNet source files, which are all C rather than C++.  Unfortunately, changing it means messing with that archaic cross-compile stuff, so we'd either need to test it on the relevant Cray systems or get the consensus necessary to delete that cross-compile hackery too (i.e. the removal from this makefile of old gasnet versions that needed it).

2021-01-16 23:13 UTC, PHHargrove commented on Makefile
> +GASNET_CFLAGS ?= -fPIC
For a "generic ethernet cluster", we normally recommend use of udp-conduit over mpi-conduit.  The AMUDP layer below udp-conduit *is* written in C++.  So it is not entirely true that GASNet is only C code.
Not sure if udp-conduit matters to you or not.

2021-01-16 23:30 UTC, PHHargrove commented on Makefile
> +	/bin/sed "s/'\(cc\)'/'\1.custom $(GASNET_CFLAGS)'/I" < $(GASNET_SOURCE_DIR)/other/contrib/$(CROSS_CONFIGURE) > $(GASNET_SOURCE_DIR)/cross-configure
Is there a reason to hard-code `/bin/sed` rather than using the `sed` found in `$PATH`?
I know this is Cray specific, but at least macOS places `sed` in `/usr/bin`, not `/bin`.

2021-01-16 23:34 UTC, PHHargrove commented
I think I agree with all of Dan's feedback and made only one other (quite minor) observation regarding `sed` (which hopefully becomes moot if one can avoid the re-write it is used to perform).

2021-01-22 20:12 UTC, bonachea commented on Makefile
> +	chmod a+x $(GASNET_BUILD_DIR)/CC.custom
Some notes from today's call: 

* The only "real" cross-configure system that currently exists is the Cray XC. GASNet versions prior to 2020.3.0 support the BlueGene/Q, but the last such machine (hosted at ALCF) was [turned off in 2019](https://www.alcf.anl.gov/news/argonne-s-mira-supercomputer-set-retire-after-years-enabling-groundbreaking-science).
* `--with-cflags`, `--with-libs` and friends were added in GASNet  1.30, which is also the oldest GASNet tarball in the master branch

2021-02-03 21:06 UTC, streichler commented on Makefile
> +GASNET_CFLAGS ?= -fPIC
this should be addressed with the latest commit - now we have GASNET_CFLAGS and GASNET_CPPFLAGS (matching the name of the `configure` arguments rather than make's usual naming)

2021-02-03 21:06 UTC, streichler commented on Makefile
> +	chmod a+x $(GASNET_BUILD_DIR)/CC.custom
all of this has been ripped up - please re-review the latest changes and let me know what you think?

2021-02-03 21:07 UTC, streichler commented on Makefile
>  GASNET_CONFIG ?= configs/config.$(CONDUIT).release
acknowledged, but config cleanup is being left for another day

2021-02-03 21:07 UTC, streichler commented on Makefile
> +	/bin/sed "s/'\(cc\)'/'\1.custom $(GASNET_CFLAGS)'/I" < $(GASNET_SOURCE_DIR)/other/contrib/$(CROSS_CONFIGURE) > $(GASNET_SOURCE_DIR)/cross-configure
this should now be moot - no sed hackery any more

2021-02-05 17:32 UTC, bonachea requested changes
I requested one rename to ensure correct operation, but otherwise looks good to me!

2021-02-05 17:57 UTC, streichler commented on Makefile
> +GASNET_CFLAGS ?= -fPIC
Ugh - I didn't see `--with-cxxflags` when I looked through the configure options.  I'll switch both this and the legion repo to use CXX instead of CPP.

2021-02-07 03:45 UTC, bonachea commented
Looks good to me - thanks for making all these improvements!

2021-02-07 03:45 UTC, bonachea approved these changes

2021-02-07 16:57 UTC, streichler commented
With a bit of history rewriting, this is merged into master with commit 90edc24.

The state of the master branch before the rewriting of the cross-configure stuff is available in the `old_crossconfig` branch should anybody need it.

Thanks again to @bonachea and @PHHargrove for their feedback.

2021-02-07 16:57 UTC, closed without merging