Add hwloc.patch to fix core binding issue exposed by OFI CXI provider
StanfordLegion/gasnet pull request #33
Opened 2024-07-18 22:48 UTC by elliottslaughter

Applying a patch by @PHHargrove to fix HWLOC core binding detection in the current GASNet release 2024.5.0. This is required to correctly use `GASNET_OFI_DEVICE_TYPE=Node` to bind NICs with the OFI CXI provider.

Some additional context about the issue is available in the following PR, which is **NOT** included in 2024.5.0 (or the attached patch), but may be included in a future GASNet release:

https://bitbucket.org/berkeleylab/gasnet/pull-requests/635/

2024-07-18 22:53 UTC, bonachea requested changes

2024-07-18 22:53 UTC, bonachea commented on Makefile
> +ifneq ($(findstring GASNet-2024.5,$(GASNET_VERSION)),)
This problem is not tied to any particular GASNet version, GASNet has been making the same hwloc call for some time now. 
What changed was the underlying behavior of libcxi that invalidated GASNet's choice.

The hwloc call in question dates back to at least 2022.3.0 (where `GASNET_OFI_DEVICE*` environment variables were added that consume this query). However I have no idea whether the patch applies cleanly to older versions.

CC: @PHHargrove

2024-07-19 00:12 UTC, elliottslaughter commented on Makefile
> +ifneq ($(findstring GASNet-2024.5,$(GASNET_VERSION)),)
I'm mostly just not sure how to write a version compare based on a string like `GASNet-YYYY.X.Z`. I assume that a future GASNet release will fix this properly and so I was preempting needing to write a version bound. I am happy to take a better version bound if there's a nice way to write that.

My plan, for whatever it is worth, was to respond to questions about binding by saying "upgrade to GASNet 2024.5.0 or newer", even though it's not *actually* tied to the GASNet version. That is admittedly a hack.

2024-07-19 01:40 UTC, bonachea commented on Makefile
> +ifneq ($(findstring GASNet-2024.5,$(GASNET_VERSION)),)
Good points. 

Make doesn't have any built-in operators suitable for version comparison, although there are certainly [ways to write version compare by invoking shell commands](https://stackoverflow.com/questions/3728372). I don't know if that qualifies as "nice".

In any case, your proposed approach seems reasonable.

2024-07-19 17:25 UTC, merged

2024-07-19 17:26 UTC, elliottslaughter commented
I'm taking this as-is. For anyone who needs this on a different version of GASNet, I would note that you can build with `make PATCHES=patches/hwloc.patch` and it will happily build with the patch.